### ISSUE TITLE
Topothèque : fonctionnalités manquantes

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#1]
La topothèque en l'état actuel manque de lien vers des pages déjà existantes ailleurs (dans des sous menus) : 

- chercher un topo
- parcourir les topo
- ajouter un topo qui n'existe pas encore
- ajouter un topo à notre liste

j'ai aussi vu à un moment qu'on pouvait voir les topo proches d'un endroit, cette fonctionnalité serait super, replacée aussi dans le contexte de recherche de topo :-)

**Comment by lucien-chastan** [comment]
Nous avons ajouté tout un ensemble de fonctionnalité dédié au topo, voici la liste des principales fonctionnalité : https://oblyk.org/guide-books/features
