### ISSUE TITLE
Nouvelle interface de saisie des ropingStatus et ascentStatus en mode edition

### ISSUE THREAD

**Issue by pectum83** [oblyk/oblyk-app#122]
La nouvelle interface de saisie des status est superbe. Plus rapide plus belle.
Je suis juste surpris que en edition (quand on veut modifier l'ascent) on ait un comportement différent qu'en création:
- le roping status ne s'adapte plus en fonction de voie/grande voie
- le choix "repetition" n'est plus dispo

J'ai vu dans le code ou était les différences et ça a l'air intentionnel mais je ne vois pas pourquoi ?

**Comment by lucien-chastan** [comment]
Hello !

Oui c'est intentionnel,
Par exemple :
Il y a des status comme 'terminer' qui fait doublon avec 'après travail' que je laisse de côté à la création d'une voie, mais il y a du passif et je ne veux pas bloquer l'édition de croix avec ce statut

Grosso modo je souhaite limiter les choix à la création pour éviter de surcharger le formulaire d'option
Et vu qu'il y a peu d'édition de croix, pour éviter d'être bloquant, je laisse tous les choix : )

Pour le mode répétions il apparaît qu'a l'ajout d'une croix sur une voie que tu as déjà faite ... mais je me rends compte qu'il n'est plus là en mode édition, c'est ce problème que tu remonte ?

**Comment by pectum83** [comment]
Oui c’est ça qui m’a bloqué quand j’ai voulu modifier des ascents que j’avais mis en ‘red point’ ou ‘sent’ et que je voulais modifier en répétition.
