### ISSUE TITLE
Problème page introuvable lors de l'édition d'un secteur

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#13]
Lors du clic sur le bouton d'édition d'un secteur déjà créé (par exemple depuis https://oblyk.org/crag-sectors/2843/les-colonnes ) 
j'arrive sur la page https://oblyk.org/a/crag-sectors/2843/les-colonnes/edit 

avec l'erreur "oops page introuvable"

Remarque : Aujourd'hui le 28/02/2022 il y a plusieurs soucis avec le serveur qui a du mal à suivre (j'ai plusieurs erreurs m'obligeant à rafraichir + quelques lenteurs par moments)

**Comment by lucien-chastan** [comment]
Corrigé !
https://github.com/oblyk/oblyk-app/commit/3e87c42beb5cafcfd4ef8e1680552ddb2607a4d1

Pour les lenteurs je pense que ça peut venir d'une mauvaise configuration de l'app qui engendrai plus de requête au serveur. J'ai remis la config pour éviter ça, je pense que ça devrait être mieux
https://github.com/oblyk/oblyk-app/commit/c36d92224666a66fdb5c786eba36bd1915120b64
