### ISSUE TITLE
BUG : lors de l'ajout de voies, le "résumé" du secteur ne les comptabilise pas

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#17]
Lors de l'ajout de lignes, le "résumé" du secteur ne les comptabilise pas.

Exemple : https://oblyk.org/crag-sectors/2857/heil-et-fines-herbes

j'ai rajouté 3 voies (pour un total de 19) mais le résumé annonce encore 16 lignes

**Comment by StephaneMichelet** [comment]
et sur certains ça en rajoute une partie : https://oblyk.org/crag-sectors/2858/cerveau-lent
était à 5
j'en rajoute 4
est maintenant à 7...

**Comment by lucien-chastan** [comment]
C'était dû à un problème de mise en cache côté API, c'est corrigé pour les suivants
Faut encore que je recharge le cache pour que ça soit rétroactif
