### ISSUE TITLE
BUG : lors de l'ajout d'un commentaire, le symbole commentaire n'apparait pas à côté de la voie 

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#18]
lors de l'ajout d'un commentaire, le symbole commentaire n'apparait pas à côté de la voie

exemple : https://oblyk.org/crag-sectors/7350/le-donjon

j'ai laissé un commentaire sur "l'appel de la pioche"

**Comment by lucien-chastan** [comment]
Même problème et même solution que pour l'issue https://github.com/oblyk/oblyk-app/issues/17
