### ISSUE TITLE
BUG : nom des contributeurs invisibles

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#19]
Lors de l'ajout d'un commentaire, le nom du contributeur ne s'affiche pas (que ce soit sur les secteurs, les voies, ...)

"Par le 28 février 2022"

**Comment by lucien-chastan** [comment]
corrigé !
https://github.com/oblyk/oblyk-app/commit/1c53bf07451ba1b07a2dece19eaa1d1fdc072394
