### ISSUE TITLE
Amélioration : Ajout d'un site (inexistant) à un topo

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#2]
Lors de la consultation d'un topo, on peut accéder aux sites associés. Or si je prends l'exemple du nouveau topo que je viens de rentrer  https://oblyk.org/guide-book-papers/292/escalade-dans-le-nord-aveyron/crags il n'y a actuellement aucuns site.

Pourriez vous ajouter un lien vers la page pour ajouter d'un site actuellement inexistant ?

**Comment by StephaneMichelet** [comment]
tu peux fermer cette demande, il y a bien ce qu'il faut maintenant ;-)

Merci !

**Comment by lucien-chastan** [comment]
Super !
j'avais oublié que je l'avais fait ^^
