### ISSUE TITLE
Ajout d'un Tag : Terrain d'Aventure

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#3]
Dans le topo Escalade dans le Nord Aveyron, j'ai quelques voies marquées Terrain d'Aventure,

pourrait on avoir un tag en conséquence pour les voies ? Merci !

**Comment by lucien-chastan** [comment]
Par terrain d'aventure moi j'entends Trad .. non ?

**Comment by StephaneMichelet** [comment]
je ne connais pas vraiment ces termes, donc je ne saurai pas dire si c'est la même chose ou différent ^^" (ça ne fait que 2 ans que je fais de l'escalade)
j'ai mis l'info lue sur le Topo telle quelle en description du coup ^^

**Comment by lucien-chastan** [comment]
Et bien trad et terrain d'aventure c'est la même chose !
Même oblyk le dit, [Trad](https://oblyk.org/words/244/trad) = [Terrain d'aventure](https://oblyk.org/words/209/terrain-d-aventure)

(ok j'ai ajouté Trad il y a quelque minutes :laughing: ... mais j'ai quand même vérifier que je ne disais de connerie : )
