### ISSUE TITLE
Accès à la liste des contributions : chargement infini

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#30]
Lorsque je veux voir l'historique des modifications d'une voie / d'un topo, et que je clique sur "1 contribution", alors la page tourne dans le vide sans jamais changer

exemple sur la page : https://oblyk.org/guide-book-papers/309/briancon-climbs-2022
je clique sur le lien : https://oblyk.org/versions/guideBookPaper/309/changes

**Comment by lucien-chastan** [comment]
Salut Stephane !

C'est un sacré hasard, j'ai remarqué et corrigé se bug hier, mais j'avais oublié de déployer le changement ^^
Je viens de déployer, et c'est bon tu as accès à la liste des contributions sur les topos / falaises, etc.

Merci de ton retour !

Lucien
