### ISSUE TITLE
Recherche avancée : les critères sont cumulatifs

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#33]
Dans le nouvel outils de recherche avancée, si on utilise le filtre "quel type d'escalade ?" et que l'on coche plusieurs croix, ben... rien n'est trouvé. On dirait que ce filtre est cumulatif.

Or si je cherche "Voie" et "Via Ferrata", je me doute que ce ne sera pas sur le même lieu (en tous cas pas chez nous). 
Du coup ce serait bien de changer le "ET" entre les différents éléments en "OU" ?
"via ferrata" OU "voie" ?

Ou sinon créer une case à cocher pour dire si on cherche l'un ET l'autre, ou l'un OU l'autre...

**Comment by lucien-chastan** [comment]
Salut Stephane

Oui tu as parfaitement raison, je voulais faire un OU et non un ET => c'est un bug

Je ne pense pas qu'il faille laisser le choix entre ET et OU ça complexifie l'interface pour un besoin que je pense personne n'a.

Je corrige ça bientôt !

**Comment by lucien-chastan** [comment]
@StephaneMichelet je me rends compte que les saisons favorables et les orientations aussi sont en mode cumulatif (a base de ET)

On est d'accord que c'est plus logique que ça soit du OU aussi ?

**Comment by StephaneMichelet** [comment]
Concernant la saison, je me dis qu'un choix exclusif est probablement suffisant ? Mais sinon, un "OU" me parait le plus pertinent.
(et au pire avec les logos ensuite on peut voir les lieux qui ont plusieurs saisons (le ET revient à voir plusieurs logos))

L'orientation je dirai aussi un "OU".

J'essaie de m'imaginer des cas où des gens voudraient par exemple une façade exposée nord ET ouest ET SUD par exemple. 
La seule chose que j'arrive à imaginer c'est que c'est pratique si tu y vas sur une journée et qu'il fait froid le matin et chaud l'après midi, je suppose ?

Mais le "ou" est plus général, ça englobe (dans mon esprit) beaucoup plus d'utilisations. (et au pire avec les logos ensuite on peut voir les lieux qui ont plusieurs orientations (le ET revient à voir plusieurs branches sur la rose des vents))

**Comment by lucien-chastan** [comment]
Ouais on est d'accord. 
J'étais partie sur des OU puis j'ai eu un doute et je voulais un avis extérieur.

Aller je pars là-dessus ! 

(Top la capture 😉)

**Comment by lucien-chastan** [comment]
C'est bon c'est en prod !
Merci de ton aide : )
