### ISSUE TITLE
Indoor : ajouter un bouton pour suppression d'un espace / d'un secteur

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#44]
Dans la salle que je gère (Figeac) j'ai décidé de changer de niveau de zoom.
ancienne réflexion : 
1 espace "salle" et ensuite des secteurs type (pan gauche, grand devers, ...) 

nouvelle structure : 
un espace par groupe de voies (pan gauche, grand devers, ...), et chaque secteur représente chaque couloir

bref j'ai un vieux espace https://oblyk.org/gyms/215/club-alpin-francais-de-figeac/spaces/25/voies-salle-londieu que je ne peux pas supprimer. Or en tant que gérant, un petit bouton serait un plus ;-)

idem pour les secteurs, quand on va sur la page de modification, une suppression serait intéressante :-)

**Comment by StephaneMichelet** [comment]
Problème réglé grâce au nouveau bouton "engrenage". 

Est-ce un choix de design pour éviter les mauvaise manip que tu ne le mets pas (le bouton supprimer) dans le menu déroulant quand on est sur les différents espaces ?

**Comment by lucien-chastan** [comment]
Hello,

Oui, pour moi c'est une option qu'on est amené à faire a la création de son topo, ou a un réarrangement
Mais c'est pas une action courante, je préfère que ça soit très volontaire de supprimer un secteur ou un espace, il faut 4 actions : aller dans la page Secteur et Espaces, cliquer sur le menu, cliquer sur supprimer, valider son choix.

**Comment by StephaneMichelet** [comment]
Je m'en doutais, et je suis d'accord, ça évite les fausses manip ! Merci de ta réponse !
