### ISSUE TITLE
Indoor : ajouter une croix ne propose pas la liste des voies

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#49]
Lorsqu'on clique sur ajouter une croix tout en haut, le comportement indoor n'est pas le même que outdoor : 

en outdoor, on choisi l'endroit, et ensuite ça nous montre la liste des voies.
en indoor ça nous propose de faire une entrée manuelle, mais ça nous montre pas la liste des voies : 

![image](https://user-images.githubusercontent.com/87929045/234253979-440a4cf9-752f-4cad-b410-66ec2ae8ae33.png)

**Comment by lucien-chastan** [comment]
Effectivement, si tu es sur la page publique de ta salle ça te redirige vers le topo, mais j'ai oublié de faire cette mécanique dans l'ajout à cette endroit !
Merci de ton aide

**Comment by lucien-chastan** [comment]
Corrigé !
