### ISSUE TITLE
Icones des crags projets et tick list

### ISSUE THREAD

**Issue by pectum83** [oblyk/oblyk-app#54]
Lorsqu'on réussi un projet et que l'on va sur la page de la falaise, l'icone du projet réussi reste l'icone projet (carré vide). Il serait plus pratique de voir que la voie est réussie.
Je vais proposer une pullrequest pour une modification.

**Comment by lucien-chastan** [comment]
Hello !
Corrigé avec la fusion de la PR https://github.com/oblyk/oblyk-app/pull/62 
Merci pour ton retour !
