### ISSUE TITLE
pas de vote de difficulté pour les GV

### ISSUE THREAD

**Issue by pectum83** [oblyk/oblyk-app#61]
Je croyais que c'était un bug mais je vois dans le code (AscentCragRouteForm.vue) que c'est intentionnel.
Quelle en est la raison ?

**Comment by lucien-chastan** [comment]
Salut,

En fait ça me semblait étrange de noter la difficulté global d'une grande voie
Il faudrait que ce soit au niveau d'une longueur, mais je trouve que c'est compliqué à implémenté.

Je me suis dit que c'est une information qu'on retrouverai dans les commentaires si elle était particulièrement coriace ou accessible
