### ISSUE TITLE
Impossible de passer un commentaire en privé lors d'une modification

### ISSUE THREAD

**Issue by StephaneMichelet** [oblyk/oblyk-app#7]
Lorsqu'on veut modifier un de ses propres commentaires déjà entrés sur le site, il n'y a pas de bouton pour le passer en privé.

**Comment by lucien-chastan** [comment]
Hello !

C'est un commentaire sur un site ou sur une croix que tu cherche à passer en privé ?

Parce que tu peux avoir un commentaire privé sur une de tes croix
Par contre un commentaire sur un site et forcément publique ..
