### ISSUE TITLE
CSV export and delimiters

### ISSUE THREAD

**Issue by glthm** [oblyk/oblyk-app#71]
Issue: Exporting a list of route as csv does not work properly when route names or descriptions contain commas (as the comma is the delimiter used for these csv exports

Proposed solution: escape commas when exporting to csv

**Comment by lucien-chastan** [comment]
Hi @glthm
The separator of .csv exports is a tab (so we should say .tsv, but nobody knows this "format").
have you tried opening the export with 'tab' as the separator?

**Comment by glthm** [comment]
Oh, ok thanks
Sorry for the inconvenience
