### ISSUE TITLE
Longueur non faites en grande voies comptent dans la difficulté des croix.

### ISSUE THREAD

**Issue by Jerome-Celle** [oblyk/oblyk-app#73]
Bonjour,
ça fait quelque temps que j'utilise Oblyk avec grand plaisir pour trouver des falaises et noter mes croix!
Mais je me permets de faire une petite remarque au niveau du carnet outdoor, si on coche une première longueur de grande voie (souvent le cas quand c'est des couennes avec 2 longueurs et qu'on ne souhaite faire que la première) au niveau du carnet ça va apparaître comme valide dans le niveau de la plus dur des longueurs même non faite.

Un exemple, sur les deux "grandes voies" je n'ai fait que les premières longueurs en 4, sauf que ça apparaît avec les 6a.
![image](https://github.com/oblyk/oblyk-app/assets/11727354/11e9e4a4-115e-43d9-bf2b-7830b22e540e)
De ce que je vois, au niveau de l'onglet analytics, c'est les bonnes longueurs qui sont prises, les deux 6a du screenshot que je n'ai pas fait ne compte pas dans mon nombre de 6a

**Comment by lucien-chastan** [comment]
Salut @Jerome-Celle 
Désolé du temps de réponse ... et merci de ton retour !

Il me semble que ce problème a été corrigé
Tu confirmes ?

**Comment by Jerome-Celle** [comment]
Hello!
Je confirme ! C'est parfait !
J'aurai pu surveiller un fermer le ticket avant 😅
