### ISSUE TITLE
"Meilleur essai" non affiché dans le carnet outdoor

### ISSUE THREAD

**Issue by maxime-gr** [oblyk/oblyk-app#75]
J'ai fait une voie que j'avais en projet, sur une autre session, je l'ai enchaînée, j'ai donc rajouter ma croix.
Dans mon carnet de croix je vois bien la voie mais le pictogramme me donne toujours la voie en projet...

(D'ailleurs dans le tooltip du prictogramme il y a aussi un soucis avec la date; "Invalid DateTime")

**Comment by pectum83** [comment]
c'est la meme demande que la #54.
Une modification qui corrige ces 2 problèmes est en cours d'approbation (https://github.com/oblyk/oblyk-app/pull/55)

**Comment by lucien-chastan** [comment]
Hello @maxime-gr !

Corrigé depuis le merge de la PR https://github.com/oblyk/oblyk-app/pull/62

Merci de ton retour : )
Et désolé pour le temps de traitement
