### ISSUE TITLE
Licence photo : cases cochées pas bonnes quand on va modifier

### ISSUE THREAD

**Issue by bohwaz** [oblyk/oblyk-app#77]
J'ai déposé une photo. J'ai coché uniquement la case "By". J'enregistre.

Quand je retourne modifier la photo, les 3 cases "By" "NC" et "ND" sont cochées.

**Comment by lucien-chastan** [comment]
ok, ça doit être un problème de `false` qui reprend la valeur par défaut : /
Mais la valeur que tu choisi est bien enregistrée
Ça devrait ce corriger sans trop de difficulté

**Comment by lucien-chastan** [comment]
C'est corrigé !
Merci d'avoir remonté le problème 🙂
