### ISSUE TITLE
Manque traduction

### ISSUE THREAD

**Issue by bohwaz** [oblyk/oblyk-app#79]
Je sélectionne la langue "FR" mais j'ai toujours des mots en anglais dans le menu :
![image](https://github.com/user-attachments/assets/2255a0da-f96f-4f7d-868b-3ef7c67837ba)

**Comment by ghusse** [comment]
Ça semble avoir été corrigé depuis

**Comment by lucien-chastan** [comment]
Oui ! https://github.com/oblyk/oblyk-app/commit/0d680f4dd7f78806462713712470d49c858f58fd

Merci du retour

**Comment by bohwaz** [comment]
il reste le "Climbing Community" à moins que ça soit volontaire ?

**Comment by lucien-chastan** [comment]
Oui c'est plus un slogan
La traduction française est moins "sonnante" je trouve

**Comment by bohwaz** [comment]
OK je comprends le choix, même si perso je trouve ça bizarre mais je survivrais ;)
