### ISSUE TITLE
Problème de rafraichissement

### ISSUE THREAD

**Issue by maxime-casoum** [oblyk/oblyk-app#8]
Quand on reste sur la même page mais qu'on change les données à afficher, les ancienne données reste affichées.

J'ai constaté le soucis avec les profils utilisateur et avec les secteurs d'une falaise.

Pour reproduire;
- Afficher le profil d'un utilisateur,
- Chercher un autre utilisateur
- L’entête de l'utilisateur a bien changé mais pas les contributions
- 
Ou;
- Afficher une falaise
- Sélectionner un secteur
- Changer de secteur
- J'ai toujours les voies du premier secteur sélectionné

**Comment by lucien-chastan** [comment]
Hello Maxime !

Merci de ton retour, on corrige ça au plus vite : )

**Comment by lucien-chastan** [comment]
Hello Maxime,
Normalement c'est corrigé : )

Merci encore de ton retour et de la précision de comment refaire le bug, c'était parfait !
