### ISSUE TITLE
Manque navigation pour se rendre sur la fiche d'une voie depuis la croix

### ISSUE THREAD

**Issue by bohwaz** [oblyk/oblyk-app#80]
Chemin suivi : bouton "ajouter une croix" -> outdoor -> je sélectionne une de mes falaises -> clic sur une voie.

Là je me rends compte qu'il y a une typo dans le nom de la voie. Mais aucun moyen de me rendre rapidement sur la fiche de la voie pour modifier, il faut que je retourne rechercher la voie dans le site via d'autres chemins.

Il serait plus pratique d'avoir un bouton qui ouvre la page de la voie (ou de la falaise à minima) depuis le formulaire de croix / autre, pour pouvoir naviguer plus facilement.

**Comment by lucien-chastan** [comment]
Ok, à ce moment la liste des voies se comporte comme des boutons pour sélectionner la voie

Ajouter un bouton à côté de chaque voie me semble 'lourd' et correspond à un usage marginal

Par contre un bouton sur le nom de la voie dans la section verte pourrait permettre cette action sans alourdir la liste

exemple : un bouton sur "Le voyage des lutins" dans la capture ci-dessous
![image](https://github.com/user-attachments/assets/575a1eca-84ae-4599-a7b1-9e0385fef5de)

Ce bouton pourrait ouvrir le panneau latéral des voies.
Comme ça il pourrait servir à voir les infos de la voie sans quitter la page d'ajout au carnet

**Comment by lucien-chastan** [comment]
Hello,
Cette fonctionnalité sera présente dans le prochain déploiement !
- Avec l'ajout d'un lien sur le nom de la falaise
- Et un bouton sur le nom de la voie pour voir le détail de la voie

![Capture d’écran du 2024-11-26 12-44-23](https://github.com/user-attachments/assets/299b76b4-47d0-4fe3-b2ff-0cb7cdfa707b)

![Capture d’écran du 2024-11-26 12-44-16](https://github.com/user-attachments/assets/9ea2d925-eeaf-49ec-8d9a-546a036ca2fc)

Merci encore pour vos suggestions !

**Comment by bohwaz** [comment]
Il me semble que ça ne répond pas au besoin exprimé, on ne peut pas modifier le nom de la voie dans la capture montrée ? Ou alors c'est le petit bouton crayon à côté de la localisation ? Si oui, instinctivement pour moi ce bouton serait pour modifier la localisation.

**Comment by lucien-chastan** [comment]
Oui le petit icon serre à modifier les informations d'une voie, que ce soit ici ou sur les autres vue détaillées d'une voie sur Oblyk
J'entends on a vu mieux en terme d'expérience utilisateur 😬

**Comment by bohwaz** [comment]
OK parfait alors ça répond au besoin au temps pour moi :) Bonne journée !
