### ISSUE TITLE
Licence absente du dépôt

### ISSUE THREAD

**Issue by leveque** [oblyk/oblyk-app#82]
Bonjour,

Quelle est la licence qui s'applique à ce logiciel et à son code source ?

Cordialement,

**Comment by lucien-chastan** [comment]
Bonjour @leveque 

Je suis en train de me documenter pour trouver la meilleurs licence.
Je peux être intéressé par des conseilles si tu as une expertise sur le sujet ?

À priori je m'oriente vers AGPL v3

**Comment by lucien-chastan** [comment]
Salut @leveque 
Oblyk api et app sont donc sur la licence AGPLV3 : )
