### ISSUE TITLE
Ordre des topos à inverser

### ISSUE THREAD

**Issue by bohwaz** [oblyk/oblyk-app#84]
Par défaut la listes des topos affiche les plus anciens en premier, ce qui ne fait pas trop de sens :

![image](https://github.com/user-attachments/assets/68f1e3cb-df41-440f-b269-bb808257e3cb)

Il faudrait plutôt afficher les plus récents en premier…

**Comment by lucien-chastan** [comment]
Oui je me suis déjà fait cette remarque, c'est à corriger !

_(au passage je note le bug sur l'icon de "contribution au financement des sites")_

**Comment by lucien-chastan** [comment]
C'est corrigé !

![image](https://github.com/user-attachments/assets/217cdd3c-bce9-4f1f-b436-f634a180f849)

Merci de ton retour !

**Comment by bohwaz** [comment]
Top, merci !
