### ISSUE TITLE
Indoor : ajout des possibilités de tri dans le topo

### ISSUE THREAD

**Issue by vbelloir** [oblyk/oblyk-app#87]
Bonjour, 
actuellement, on peut trier par secteur, par cotation et par date d'ouverture, mais ça serait bien de pouvoir trier par popularité (le nombre de croix) et par nombre de croix par voies. L'iodée est ainsi de voir quelles les voies les plus populaires et les plus pratiquées, et inversement, celles qui ne plaisent pas.

ça existe peut-être ailleurs dans Oblyk, mais je n'ai pas trouvé.

Merci pour le job, c'est top, et ça commence à être utilisé par nos adhérents.

**Comment by ghusse** [comment]
Pour les administrateurs, il est possible de trier par nombre de croix dans la vue tableau associée à un espace. Est-ce que ta demande concernait les admins ?

**Comment by vbelloir** [comment]
Hum, oui, très juste, je n'avais pas fait attention à ce point.

Donc ok pour la partie admin, mais je pense que ça peut être intéressant aussi pour la vue publique:

![image](https://github.com/user-attachments/assets/1beba147-fa8e-4a83-ad74-bf3b03855c83)

**Comment by lucien-chastan** [comment]
Oui, je pense qu'on peux ajouter les tries suivants : 
- nombre de réalisation
- nombre de commentaire
- nombre de like

Je trouve ces trois trie supplémentaire pertinent
 
Mais je crains qu'avec les 4 tries déjà possibles (secteur, date d'ouverture, cotation et couleur) ça fasse trop ...

Peut-être qu'une séparation par un trait horizontal (comme les lignes démonter) pourrais aider à comprendre les tries sur les propriété des voies, des tries sur l'activité des grimpeurs

**Comment by ghusse** [comment]
Les nouveaux tris ont été ajouté à l'app ! (On peut fermer le ticket :angel:)
