### ISSUE TITLE
Croix sans statut de l'ascension

### ISSUE THREAD

**Issue by Victor-Morel** [oblyk/oblyk-app#9]
L'ajout d'une croix sans statut de l'ascension est permise par le site, mais l'ajout n'est pas inscrit dans la liste des croix si c'est le cas (et un message non-destiné aux utilisateurices est affiché). 
![image](https://user-images.githubusercontent.com/6717197/128009474-6de18eb3-5f54-45da-a98f-e09982767be3.jpeg)

**Comment by lucien-chastan** [comment]
ok corrigé !
