### ISSUE TITLE
Typo : uniquement _pas_ au lieu de _uniquement par_ dans le process d'inscription

### ISSUE THREAD

**Issue by Pacos** [oblyk/oblyk-app#92]
Il y a une typo dans le processus d'inscription, lors de la description des options liées au profil privé. Il est écrit :
```
uniquement pas vos abonné·es
```
Au lieu de :
```
uniquement par vos abonné·es
```

**Comment by lucien-chastan** [comment]
Mergé !
Déployé prochainement, je clos
